//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line of tokens must be informed.
        /// </summary>
        internal static string LoadTokensEmpty {
            get {
                return ResourceManager.GetString("LoadTokensEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered value does not contain the separator.
        /// </summary>
        internal static string LoadTokensNotContainsSeparator {
            get {
                return ResourceManager.GetString("LoadTokensNotContainsSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name must be informed.
        /// </summary>
        internal static string NoClassNameValue {
            get {
                return ResourceManager.GetString("NoClassNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No end value.
        /// </summary>
        internal static string NoEndValue {
            get {
                return ResourceManager.GetString("NoEndValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No input value.
        /// </summary>
        internal static string NoInputValue {
            get {
                return ResourceManager.GetString("NoInputValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No output value.
        /// </summary>
        internal static string NoOutputValue {
            get {
                return ResourceManager.GetString("NoOutputValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity to replicate is empty.
        /// </summary>
        internal static string NoQuantityToReplicate {
            get {
                return ResourceManager.GetString("NoQuantityToReplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No replace token value.
        /// </summary>
        internal static string NoReplaceToken {
            get {
                return ResourceManager.GetString("NoReplaceToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No separator value.
        /// </summary>
        internal static string NoSeparatorValue {
            get {
                return ResourceManager.GetString("NoSeparatorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No start value.
        /// </summary>
        internal static string NoStartValue {
            get {
                return ResourceManager.GetString("NoStartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No template value.
        /// </summary>
        internal static string NoTemplateData {
            get {
                return ResourceManager.GetString("NoTemplateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Type Name.
        /// </summary>
        internal static string NoTypeNameData {
            get {
                return ResourceManager.GetString("NoTypeNameData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Variable Name.
        /// </summary>
        internal static string NoVariableNameData {
            get {
                return ResourceManager.GetString("NoVariableNameData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of tokens different from items per line.
        /// </summary>
        internal static string NumberDifferentReplaceToken {
            get {
                return ResourceManager.GetString("NumberDifferentReplaceToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON is Object query from select Array must be informed.
        /// </summary>
        internal static string ParserJsonNoQuery {
            get {
                return ResourceManager.GetString("ParserJsonNoQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity to replicate must be integer.
        /// </summary>
        internal static string QuantityToReplicateInt {
            get {
                return ResourceManager.GetString("QuantityToReplicateInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token already added.
        /// </summary>
        internal static string ReplaceTokenAlready {
            get {
                return ResourceManager.GetString("ReplaceTokenAlready", resourceCulture);
            }
        }
    }
}
